tab = ('América-MG', 'Athletico-PR', 'Atlético-GO', 'Atlético-MG', 'Bahia', 'Bragantino', 'Ceará', 'Chapecoense', 'Corinthians', 'Cuiabá', 'Flamengo', 'Fluminense', 'Fortaleza', 'Grêmio', 'Internacional', 'Juventude', 'Palmeiras', 'Santos', 'São Paulo', 'Sport')
print('-=' * 30)
print(f'Lista de times do brasileirão:  {tab}')
print('-=' * 30)
print(f'Os 5 primeiros são {tab[:5]}')
print('-=' * 30)
print(f'Os 4 útimos são {tab[-4:]}')
print('-=' * 30)
print(f'Times em ordem alfabetica {sorted(tab)}')
print('\033[32m-=\033[m' * 30)
print(f'Posição da \033[32mChapecoense\033[m {tab.index( "Chapecoense" ) + 1}')
